/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_vpnlogin (void)
{
  GtkWidget *vpnlogin;
  GtkWidget *mainVBox;
  GtkWidget *mainNotebook;
  GtkWidget *vbox2;
  GtkWidget *gwMainTable;
  GtkWidget *profileLabel;
  GtkWidget *profileCombo;
  GtkWidget *gwtypeLabel;
  GtkWidget *gwtypeCombo;
  GtkWidget *gwLabel;
  GtkWidget *authenticateLabel;
  GtkWidget *authenticateCombo;
  GtkWidget *gwEntry;
  GtkWidget *authFrame;
  GtkWidget *alignment4;
  GtkWidget *table2;
  GtkWidget *auth1label;
  GtkWidget *auth1Combo;
  GtkWidget *auth2Label;
  GtkWidget *auth2Entry;
  GtkWidget *authenticateHeadingLabel;
  GtkWidget *gwPanel;
  GtkWidget *connPanelVBox;
  GtkWidget *ConnectionStatusFrame;
  GtkWidget *alignment13;
  GtkWidget *alignment14;
  GtkWidget *table9;
  GtkWidget *hseparator1;
  GtkWidget *label91;
  GtkWidget *connStatusLabel;
  GtkWidget *connLabel1;
  GtkWidget *connLabel;
  GtkWidget *connStatusFrameLabel;
  GtkWidget *connDetailsTable;
  GtkWidget *hseparator2;
  GtkWidget *connIPAddress;
  GtkWidget *connUptime;
  GtkWidget *label109;
  GtkWidget *label108;
  GtkWidget *connectionPanel;
  GtkWidget *dynamicsVbox;
  GtkWidget *frame3;
  GtkWidget *alignment6;
  GtkWidget *table4;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *saStasLabel;
  GtkWidget *frame4;
  GtkWidget *alignment7;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview2;
  GtkWidget *saDetailsLabel;
  GtkWidget *dynamicsPanel;
  GtkWidget *profileManagerVbox;
  GtkWidget *vbox1;
  GtkWidget *table21;
  GtkWidget *pmProfileLabel;
  GtkWidget *pmprofileCombo;
  GtkWidget *pmNotebook;
  GtkWidget *pmGeneralTable;
  GtkWidget *pmProfileNameLabel;
  GtkWidget *pmprofileNameEntry;
  GtkWidget *pmGwTypeLabel;
  GtkWidget *pmAuthframe;
  GtkWidget *alignment15;
  GtkWidget *table23;
  GtkWidget *pmUserCertLabel;
  GtkWidget *pmauthCombo;
  GtkWidget *label96;
  GtkWidget *pmAuthenticateLabel;
  GtkWidget *pmauthenticateCombo;
  GtkWidget *pmGwIP;
  GtkWidget *pmgwtypeCombo;
  GtkWidget *pmGwEntry;
  GtkWidget *label110;
  GtkWidget *pmauthtypeCombo;
  GtkWidget *label76;
  GtkWidget *table25;
  GtkWidget *pmPh1DhLabel;
  GtkWidget *pmPh2PfsLabel;
  GtkWidget *label116;
  GtkWidget *vbox3;
  GtkWidget *addbtn;
  GtkWidget *alignment20;
  GtkWidget *hbox15;
  GtkWidget *image19;
  GtkWidget *label118;
  GtkWidget *rembtn;
  GtkWidget *alignment21;
  GtkWidget *hbox16;
  GtkWidget *image20;
  GtkWidget *label119;
  GtkWidget *scrolledwindow7;
  GtkWidget *ph2treeview;
  GtkWidget *pmPh1ModeLabel;
  GtkWidget *pmPh1ModeCombo;
  GtkWidget *pmPh1DhCombo;
  GtkWidget *pmPh2DhCombo;
  GtkWidget *label114;
  GtkWidget *hbox6;
  GtkWidget *hbuttonbox5;
  GtkWidget *pmCancelBtn;
  GtkWidget *hbuttonbox6;
  GtkWidget *pmRembtn;
  GtkWidget *pmSavBtn;
  GtkWidget *pmAddBtn;
  GtkWidget *profilePanel;
  GtkWidget *mainWindowHbox;
  GtkWidget *hbuttonbox3;
  GtkWidget *mainHelpBtn;
  GtkWidget *hbuttonbox2;
  GtkWidget *mainDisconnectBtn;
  GtkWidget *alignment17;
  GtkWidget *hbox12;
  GtkWidget *image15;
  GtkWidget *label103;
  GtkWidget *mainCancelBtn;
  GtkWidget *mainConnectBtn;
  GtkWidget *alignment18;
  GtkWidget *hbox13;
  GtkWidget *image16;
  GtkWidget *label104;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;
  GtkWidget *pmSplitTunnelCheckBtn;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  vpnlogin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (vpnlogin), 12);
  gtk_window_set_title (GTK_WINDOW (vpnlogin), _("VPN Client for Linux"));

  mainVBox = gtk_vbox_new (FALSE, 6);
  gtk_widget_show (mainVBox);
  gtk_container_add (GTK_CONTAINER (vpnlogin), mainVBox);

  mainNotebook = gtk_notebook_new ();
  gtk_widget_show (mainNotebook);
  gtk_box_pack_start (GTK_BOX (mainVBox), mainNotebook, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (mainNotebook), 1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (mainNotebook), vbox2);

  gwMainTable = gtk_table_new (5, 2, FALSE);
  gtk_widget_show (gwMainTable);
  gtk_box_pack_start (GTK_BOX (vbox2), gwMainTable, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (gwMainTable), 12);
  gtk_table_set_row_spacings (GTK_TABLE (gwMainTable), 12);
  gtk_table_set_col_spacings (GTK_TABLE (gwMainTable), 9);

  profileLabel = gtk_label_new_with_mnemonic (_("_Profile name:"));
  gtk_widget_show (profileLabel);
  gtk_table_attach (GTK_TABLE (gwMainTable), profileLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (profileLabel), 0, 0.5);

  profileCombo = gtk_combo_box_new_text ();
  gtk_widget_show (profileCombo);
  gtk_table_attach (GTK_TABLE (gwMainTable), profileCombo, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (profileCombo), _("Select a profile"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (profileCombo), _("Profile manager"));

  gwtypeLabel = gtk_label_new_with_mnemonic (_("Gateway _type:"));
  gtk_table_attach (GTK_TABLE (gwMainTable), gwtypeLabel, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (gwtypeLabel), 0, 0.5);

  gwtypeCombo = gtk_combo_box_new_text ();
  gtk_table_attach (GTK_TABLE (gwMainTable), gwtypeCombo, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (gwtypeCombo), _("Choose gateway type"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gwtypeCombo), _("Standard IPsec gateway"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (gwtypeCombo), _("nortel"));

  gwLabel = gtk_label_new_with_mnemonic (_("_Gateway:"));
  gtk_widget_show (gwLabel);
  gtk_table_attach (GTK_TABLE (gwMainTable), gwLabel, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (gwLabel), 0, 0.5);

  authenticateLabel = gtk_label_new_with_mnemonic (_("Authe_nticate:"));
  gtk_table_attach (GTK_TABLE (gwMainTable), authenticateLabel, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (authenticateLabel), 0, 0.5);

  authenticateCombo = gtk_combo_box_new_text ();
  gtk_table_attach (GTK_TABLE (gwMainTable), authenticateCombo, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (authenticateCombo), _("Using certificate"));

  gwEntry = gtk_entry_new ();
  gtk_widget_show (gwEntry);
  gtk_table_attach (GTK_TABLE (gwMainTable), gwEntry, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  authFrame = gtk_frame_new (NULL);
  gtk_widget_show (authFrame);
  gtk_table_attach (GTK_TABLE (gwMainTable), authFrame, 0, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (authFrame), GTK_SHADOW_NONE);

  alignment4 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (authFrame), alignment4);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment4), 0, 0, 12, 0);

  table2 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (alignment4), table2);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 12);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 13);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 6);

  auth1label = gtk_label_new_with_mnemonic (_("_User certificate:"));
  gtk_widget_show (auth1label);
  gtk_table_attach (GTK_TABLE (table2), auth1label, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (auth1label), 0, 0.5);

  auth1Combo = gtk_combo_box_new_text ();
  gtk_widget_show (auth1Combo);
  gtk_table_attach (GTK_TABLE (table2), auth1Combo, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (auth1Combo), _("Choose certificate"));

  auth2Label = gtk_label_new_with_mnemonic (_("P_assword:"));
  gtk_widget_show (auth2Label);
  gtk_table_attach (GTK_TABLE (table2), auth2Label, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (auth2Label), 0, 0.5);

  auth2Entry = gtk_entry_new ();
  gtk_widget_show (auth2Entry);
  gtk_table_attach (GTK_TABLE (table2), auth2Entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_visibility (GTK_ENTRY (auth2Entry), FALSE);

  authenticateHeadingLabel = gtk_label_new (_("<b>Certificate</b>"));
  gtk_widget_show (authenticateHeadingLabel);
  gtk_frame_set_label_widget (GTK_FRAME (authFrame), authenticateHeadingLabel);
  gtk_widget_set_size_request (authenticateHeadingLabel, -1, 29);
  gtk_label_set_use_markup (GTK_LABEL (authenticateHeadingLabel), TRUE);

  gwPanel = gtk_label_new (_("Gateway"));
  gtk_widget_show (gwPanel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (mainNotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (mainNotebook), 0), gwPanel);
  GTK_WIDGET_SET_FLAGS (gwPanel, GTK_CAN_FOCUS);

  connPanelVBox = gtk_vbox_new (FALSE, 12);
  gtk_container_add (GTK_CONTAINER (mainNotebook), connPanelVBox);
  gtk_container_set_border_width (GTK_CONTAINER (connPanelVBox), 12);
  gtk_widget_set_sensitive (connPanelVBox, FALSE);

  ConnectionStatusFrame = gtk_frame_new (NULL);
  gtk_widget_show (ConnectionStatusFrame);
  gtk_box_pack_start (GTK_BOX (connPanelVBox), ConnectionStatusFrame, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (ConnectionStatusFrame), GTK_SHADOW_NONE);

  alignment13 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (ConnectionStatusFrame), alignment13);

  alignment14 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (alignment13), alignment14);

  table9 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table9);
  gtk_container_add (GTK_CONTAINER (alignment14), table9);
  gtk_table_set_row_spacings (GTK_TABLE (table9), 7);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_table_attach (GTK_TABLE (table9), hseparator1, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label91 = gtk_label_new_with_mnemonic (_("IKE event                    "));
  gtk_widget_show (label91);
  gtk_table_attach (GTK_TABLE (table9), label91, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 1, 3);
  gtk_misc_set_alignment (GTK_MISC (label91), 0, 0.5);

  connStatusLabel = gtk_label_new ("");
  gtk_widget_show (connStatusLabel);
  gtk_table_attach (GTK_TABLE (table9), connStatusLabel, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (connStatusLabel), 0, 0.5);

  connLabel1 = gtk_label_new (_("Connection Status       "));
  gtk_widget_show (connLabel1);
  gtk_table_attach (GTK_TABLE (table9), connLabel1, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (connLabel1), 0, 0.5);

  connLabel = gtk_label_new (_("Not connected"));
  gtk_widget_show (connLabel);
  gtk_table_attach (GTK_TABLE (table9), connLabel, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (connLabel), 0, 0.5);

  connStatusFrameLabel = gtk_label_new (_("<b>Connection details</b>"));
  gtk_widget_show (connStatusFrameLabel);
  gtk_frame_set_label_widget (GTK_FRAME (ConnectionStatusFrame), connStatusFrameLabel);
  gtk_label_set_use_markup (GTK_LABEL (connStatusFrameLabel), TRUE);

  connDetailsTable = gtk_table_new (4, 2, FALSE);
  gtk_box_pack_start (GTK_BOX (connPanelVBox), connDetailsTable, FALSE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (connDetailsTable), 7);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_table_attach (GTK_TABLE (connDetailsTable), hseparator2, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  connIPAddress = gtk_label_new ("");
  gtk_widget_show (connIPAddress);
  gtk_table_attach (GTK_TABLE (connDetailsTable), connIPAddress, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (connIPAddress), 0, 0.5);

  connUptime = gtk_label_new (_("0 00:00:00"));
  gtk_widget_show (connUptime);
  gtk_table_attach (GTK_TABLE (connDetailsTable), connUptime, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (connUptime), 0, 0.5);

  label109 = gtk_label_new (_("Duration"));
  gtk_widget_show (label109);
  gtk_table_attach (GTK_TABLE (connDetailsTable), label109, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label109), 0, 0.5);

  label108 = gtk_label_new (_("Gateway IP Address"));
  gtk_widget_show (label108);
  gtk_table_attach (GTK_TABLE (connDetailsTable), label108, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label108), 0, 0.5);

  connectionPanel = gtk_label_new (_("Connection details"));
  gtk_widget_show (connectionPanel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (mainNotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (mainNotebook), 1), connectionPanel);

  dynamicsVbox = gtk_vbox_new (FALSE, 12);
  gtk_container_add (GTK_CONTAINER (mainNotebook), dynamicsVbox);
  gtk_container_set_border_width (GTK_CONTAINER (dynamicsVbox), 12);
  gtk_widget_set_sensitive (dynamicsVbox, FALSE);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (dynamicsVbox), frame3, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame3), GTK_SHADOW_NONE);

  alignment6 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (frame3), alignment6);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment6), 0, 0, 12, 0);

  table4 = gtk_table_new (4, 2, TRUE);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (alignment6), table4);
  gtk_container_set_border_width (GTK_CONTAINER (table4), 12);
  gtk_table_set_row_spacings (GTK_TABLE (table4), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 6);

  label21 = gtk_label_new (_("IKE SA:"));
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table4), label21, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  label22 = gtk_label_new (_("IPsec SA:"));
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table4), label22, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  label25 = gtk_label_new (_("Don't Know"));
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table4), label25, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  label26 = gtk_label_new (_("Don't Know"));
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table4), label26, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  label27 = gtk_label_new (_("Total IKE SAs:"));
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table4), label27, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  label28 = gtk_label_new (_("Don't Know"));
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table4), label28, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  label29 = gtk_label_new (_("Total IPsec SAs:        "));
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table4), label29, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  label30 = gtk_label_new (_("Don't Know"));
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table4), label30, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  saStasLabel = gtk_label_new (_("<b>SA Statistics</b>"));
  gtk_widget_show (saStasLabel);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), saStasLabel);
  gtk_label_set_use_markup (GTK_LABEL (saStasLabel), TRUE);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (dynamicsVbox), frame4, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame4), GTK_SHADOW_NONE);

  alignment7 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (frame4), alignment7);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment7), 0, 0, 12, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (alignment7), scrolledwindow2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_ETCHED_IN);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview2);

  saDetailsLabel = gtk_label_new (_("<b>SA Details</b>"));
  gtk_widget_show (saDetailsLabel);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), saDetailsLabel);
  gtk_label_set_use_markup (GTK_LABEL (saDetailsLabel), TRUE);

  dynamicsPanel = gtk_label_new (_("Dynamics"));
  gtk_widget_show (dynamicsPanel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (mainNotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (mainNotebook), 2), dynamicsPanel);

  profileManagerVbox = gtk_vbox_new (FALSE, 0);
  gtk_container_add (GTK_CONTAINER (mainNotebook), profileManagerVbox);
  gtk_widget_set_sensitive (profileManagerVbox, FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (profileManagerVbox), vbox1, TRUE, TRUE, 0);

  table21 = gtk_table_new (1, 2, TRUE);
  gtk_widget_show (table21);
  gtk_box_pack_start (GTK_BOX (vbox1), table21, FALSE, FALSE, 0);

  pmProfileLabel = gtk_label_new_with_mnemonic (_("      Pro_file : "));
  gtk_widget_show (pmProfileLabel);
  gtk_table_attach (GTK_TABLE (table21), pmProfileLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pmProfileLabel), 0, 0.5);

  pmprofileCombo = gtk_combo_box_new_text ();
  gtk_widget_show (pmprofileCombo);
  gtk_table_attach (GTK_TABLE (table21), pmprofileCombo, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (pmprofileCombo), _(" - Choose profile -"));

  pmNotebook = gtk_notebook_new ();
  gtk_box_pack_start (GTK_BOX (vbox1), pmNotebook, TRUE, TRUE, 0);

  pmGeneralTable = gtk_table_new (6, 2, FALSE);
  gtk_widget_show (pmGeneralTable);
  gtk_container_add (GTK_CONTAINER (pmNotebook), pmGeneralTable);
  gtk_table_set_row_spacings (GTK_TABLE (pmGeneralTable), 5);
  gtk_table_set_col_spacings (GTK_TABLE (pmGeneralTable), 7);

  pmProfileNameLabel = gtk_label_new_with_mnemonic (_("Profile _name :       "));
  gtk_widget_show (pmProfileNameLabel);
  gtk_table_attach (GTK_TABLE (pmGeneralTable), pmProfileNameLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pmProfileNameLabel), 0, 0.5);

  pmprofileNameEntry = gtk_entry_new ();
  gtk_widget_show (pmprofileNameEntry);
  gtk_table_attach (GTK_TABLE (pmGeneralTable), pmprofileNameEntry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  pmGwTypeLabel = gtk_label_new_with_mnemonic (_("Gateway _type :"));
  gtk_widget_show (pmGwTypeLabel);
  gtk_table_attach (GTK_TABLE (pmGeneralTable), pmGwTypeLabel, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pmGwTypeLabel), 0, 0.5);

  pmAuthframe = gtk_frame_new (NULL);
  gtk_widget_show (pmAuthframe);
  gtk_table_attach (GTK_TABLE (pmGeneralTable), pmAuthframe, 0, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (pmAuthframe), GTK_SHADOW_NONE);

  alignment15 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (pmAuthframe), alignment15);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment15), 0, 0, 12, 0);

  table23 = gtk_table_new (1, 2, FALSE);
  gtk_widget_show (table23);
  gtk_container_add (GTK_CONTAINER (alignment15), table23);
  gtk_container_set_border_width (GTK_CONTAINER (table23), 7);
  gtk_table_set_row_spacings (GTK_TABLE (table23), 6);
  gtk_table_set_col_spacings (GTK_TABLE (table23), 6);

  pmUserCertLabel = gtk_label_new_with_mnemonic (_("_User certificate:"));
  gtk_widget_show (pmUserCertLabel);
  gtk_table_attach (GTK_TABLE (table23), pmUserCertLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pmUserCertLabel), 0, 0.5);

  pmauthCombo = gtk_combo_box_new_text ();
  gtk_widget_show (pmauthCombo);
  gtk_table_attach (GTK_TABLE (table23), pmauthCombo, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (pmauthCombo), _("Choose certificate"));

  label96 = gtk_label_new (_("<b>Certificate</b>"));
  gtk_widget_show (label96);
  gtk_frame_set_label_widget (GTK_FRAME (pmAuthframe), label96);
  gtk_widget_set_size_request (label96, -1, 28);
  gtk_label_set_use_markup (GTK_LABEL (label96), TRUE);

  pmAuthenticateLabel = gtk_label_new_with_mnemonic (_("_Authenticate using : "));
  gtk_widget_show (pmAuthenticateLabel);
  gtk_table_attach (GTK_TABLE (pmGeneralTable), pmAuthenticateLabel, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pmAuthenticateLabel), 0, 0.5);

  pmauthenticateCombo = gtk_combo_box_new_text ();
  gtk_widget_show (pmauthenticateCombo);
  gtk_table_attach (GTK_TABLE (pmGeneralTable), pmauthenticateCombo, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (pmauthenticateCombo), _("X.509 certificate"));

  pmGwIP = gtk_label_new_with_mnemonic (_("_Gateway : "));
  gtk_widget_show (pmGwIP);
  gtk_table_attach (GTK_TABLE (pmGeneralTable), pmGwIP, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pmGwIP), 0, 0.5);

  pmgwtypeCombo = gtk_combo_box_new_text ();
  gtk_widget_show (pmgwtypeCombo);
  gtk_table_attach (GTK_TABLE (pmGeneralTable), pmgwtypeCombo, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (pmgwtypeCombo), _("Choose gateway"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (pmgwtypeCombo), _("Standard IPsec gateway"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (pmgwtypeCombo), _("nortel"));

  pmGwEntry = gtk_entry_new ();
  gtk_widget_show (pmGwEntry);
  gtk_table_attach (GTK_TABLE (pmGeneralTable), pmGwEntry, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label110 = gtk_label_new_with_mnemonic (_("Authentication type :"));
  gtk_widget_show (label110);
  gtk_table_attach (GTK_TABLE (pmGeneralTable), label110, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label110), 0, 0.5);

  pmauthtypeCombo = gtk_combo_box_new_text ();
  gtk_widget_show (pmauthtypeCombo);
  gtk_table_attach (GTK_TABLE (pmGeneralTable), pmauthtypeCombo, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (pmauthtypeCombo), _("Extended Authentication"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (pmauthtypeCombo), _("X.509 Certificate"));

  label76 = gtk_label_new (_("General"));
  gtk_widget_show (label76);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (pmNotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (pmNotebook), 0), label76);

  table25 = gtk_table_new (6, 3, FALSE);
  gtk_widget_show (table25);
  gtk_container_add (GTK_CONTAINER (pmNotebook), table25);
  gtk_table_set_row_spacings (GTK_TABLE (table25), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table25), 2);

  pmPh1DhLabel = gtk_label_new (_("DH Group"));
  gtk_widget_show (pmPh1DhLabel);
  gtk_table_attach (GTK_TABLE (table25), pmPh1DhLabel, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pmPh1DhLabel), 0, 0.5);

  pmPh2PfsLabel = gtk_label_new (_("PFS Group"));
  gtk_widget_show (pmPh2PfsLabel);
  gtk_table_attach (GTK_TABLE (table25), pmPh2PfsLabel, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pmPh2PfsLabel), 0, 0.5);

  pmSplitTunnelCheckBtn = gtk_check_button_new_with_label ("Disable split tunnel");
  gtk_widget_show (pmSplitTunnelCheckBtn);
  gtk_table_attach (GTK_TABLE (table25), pmSplitTunnelCheckBtn, 0, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label116 = gtk_label_new (_("Use VPN for following Networks"));
  gtk_widget_show (label116);
  gtk_table_attach (GTK_TABLE (table25), label116, 0, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label116), 0, 0.5);

  vbox3 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (vbox3);
  gtk_table_attach (GTK_TABLE (table25), vbox3, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  addbtn = gtk_button_new ();
  gtk_widget_show (addbtn);
  gtk_box_pack_start (GTK_BOX (vbox3), addbtn, FALSE, FALSE, 0);
  gtk_button_set_relief (GTK_BUTTON (addbtn), GTK_RELIEF_HALF);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (addbtn), alignment20);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox15);

  image19 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox15), image19, FALSE, FALSE, 0);

  label118 = gtk_label_new_with_mnemonic ("Add");
  gtk_widget_show (label118);
  gtk_box_pack_start (GTK_BOX (hbox15), label118, FALSE, FALSE, 0);

  rembtn = gtk_button_new ();
  gtk_widget_show (rembtn);
  gtk_box_pack_start (GTK_BOX (vbox3), rembtn, FALSE, FALSE, 0);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (rembtn), alignment21);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox16);

  image20 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox16), image20, FALSE, FALSE, 0);

  label119 = gtk_label_new_with_mnemonic ("Remove");
  gtk_widget_show (label119);
  gtk_box_pack_start (GTK_BOX (hbox16), label119, FALSE, FALSE, 0);

  scrolledwindow7 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow7);
  gtk_table_attach (GTK_TABLE (table25), scrolledwindow7, 0, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow7), GTK_SHADOW_IN);

  ph2treeview = gtk_tree_view_new ();
  gtk_widget_show (ph2treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow7), ph2treeview);

  pmPh1ModeLabel = gtk_label_new (_("Exchange Mode"));
  gtk_widget_show (pmPh1ModeLabel);
  gtk_table_attach (GTK_TABLE (table25), pmPh1ModeLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pmPh1ModeLabel), 0, 0.5);

  pmPh1ModeCombo = gtk_combo_box_new_text ();
  gtk_widget_show (pmPh1ModeCombo);
  gtk_table_attach (GTK_TABLE (table25), pmPh1ModeCombo, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (pmPh1ModeCombo, FALSE);
  gtk_combo_box_append_text (GTK_COMBO_BOX (pmPh1ModeCombo), _("Aggressive"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (pmPh1ModeCombo), _("Main"));

  pmPh1DhCombo = gtk_combo_box_new_text ();
  gtk_widget_show (pmPh1DhCombo);
  gtk_table_attach (GTK_TABLE (table25), pmPh1DhCombo, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (pmPh1DhCombo), _("768 bits (DH 1)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (pmPh1DhCombo), _("1024 bits (DH 2)"));

  pmPh2DhCombo = gtk_combo_box_new_text ();
  gtk_widget_show (pmPh2DhCombo);
  gtk_table_attach (GTK_TABLE (table25), pmPh2DhCombo, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (pmPh2DhCombo), _("Off"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (pmPh2DhCombo), _("768 bits (PFS 1)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (pmPh2DhCombo), _("1024 bits (PFS 2)"));

  label114 = gtk_label_new (_("Additional"));
  gtk_widget_show (label114);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (pmNotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (pmNotebook), 1), label114);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (profileManagerVbox), hbox6, FALSE, FALSE, 0);

  hbuttonbox5 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox5);
  gtk_box_pack_start (GTK_BOX (hbox6), hbuttonbox5, TRUE, TRUE, 0);

  pmCancelBtn = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (pmCancelBtn);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), pmCancelBtn);
  GTK_WIDGET_SET_FLAGS (pmCancelBtn, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, pmCancelBtn, _("Go back to main page"), NULL);

  hbuttonbox6 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox6);
  gtk_box_pack_start (GTK_BOX (hbox6), hbuttonbox6, TRUE, TRUE, 0);

  pmRembtn = gtk_button_new_from_stock ("gtk-remove");
  gtk_widget_show (pmRembtn);
  gtk_container_add (GTK_CONTAINER (hbuttonbox6), pmRembtn);
  gtk_widget_set_sensitive (pmRembtn, FALSE);
  GTK_WIDGET_SET_FLAGS (pmRembtn, GTK_CAN_DEFAULT);

  pmSavBtn = gtk_button_new_from_stock ("gtk-save");
  gtk_widget_show (pmSavBtn);
  gtk_container_add (GTK_CONTAINER (hbuttonbox6), pmSavBtn);
  gtk_widget_set_sensitive (pmSavBtn, FALSE);
  GTK_WIDGET_SET_FLAGS (pmSavBtn, GTK_CAN_DEFAULT);

  pmAddBtn = gtk_button_new_from_stock ("gtk-add");
  gtk_widget_show (pmAddBtn);
  gtk_container_add (GTK_CONTAINER (hbuttonbox6), pmAddBtn);
  GTK_WIDGET_SET_FLAGS (pmAddBtn, GTK_CAN_DEFAULT);

  profilePanel = gtk_label_new (_("Profile manager"));
  gtk_widget_show (profilePanel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (mainNotebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (mainNotebook), 3), profilePanel);
  GTK_WIDGET_SET_FLAGS (profilePanel, GTK_CAN_FOCUS);

  mainWindowHbox = gtk_hbox_new (FALSE, 12);
  gtk_widget_show (mainWindowHbox);
  gtk_box_pack_start (GTK_BOX (mainVBox), mainWindowHbox, FALSE, FALSE, 0);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (mainWindowHbox), hbuttonbox3, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_START);

  mainHelpBtn = gtk_button_new_from_stock ("gtk-help");
  gtk_widget_show (mainHelpBtn);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), mainHelpBtn);
  GTK_WIDGET_SET_FLAGS (mainHelpBtn, GTK_CAN_DEFAULT);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (mainWindowHbox), hbuttonbox2, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox2), 6);

  mainDisconnectBtn = gtk_button_new ();
  gtk_widget_show (mainDisconnectBtn);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), mainDisconnectBtn);
  GTK_WIDGET_SET_FLAGS (mainDisconnectBtn, GTK_CAN_DEFAULT);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (mainDisconnectBtn), alignment17);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox12);

  image15 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox12), image15, FALSE, FALSE, 0);

  label103 = gtk_label_new_with_mnemonic (_("_Disconnect"));
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (hbox12), label103, FALSE, FALSE, 0);

  mainCancelBtn = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (mainCancelBtn);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), mainCancelBtn);
  GTK_WIDGET_SET_FLAGS (mainCancelBtn, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (mainCancelBtn, "clicked", accel_group,
                              GDK_Escape, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  mainConnectBtn = gtk_button_new ();
  gtk_widget_show (mainConnectBtn);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), mainConnectBtn);
  GTK_WIDGET_SET_FLAGS (mainConnectBtn, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (mainConnectBtn, "clicked", accel_group,
                              GDK_Return, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (mainConnectBtn), alignment18);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox13);

  image16 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox13), image16, FALSE, FALSE, 0);

  label104 = gtk_label_new_with_mnemonic (_("C_onnect"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox13), label104, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) vpnlogin, "show",
                    G_CALLBACK (on_vpnlogin_show),
                    NULL);
  g_signal_connect ((gpointer) vpnlogin, "destroy",
                    G_CALLBACK (on_vpnlogin_destroy),
                    NULL);
  g_signal_connect ((gpointer) gwtypeCombo, "changed",
                    G_CALLBACK (on_gwtypeCombo_changed),
                    NULL);
  g_signal_connect ((gpointer) auth1Combo, "changed",
                    G_CALLBACK (on_auth1Combo_changed),
                    NULL);
  g_signal_connect ((gpointer) pmauthCombo, "changed",
                    G_CALLBACK (on_auth1Combo_changed),
                    NULL);
  g_signal_connect ((gpointer) pmgwtypeCombo, "changed",
                    G_CALLBACK (on_pmgwtypeCombo_changed),
                    NULL);
  g_signal_connect ((gpointer) pmauthtypeCombo, "changed",
                    G_CALLBACK (on_pmauthtypeCombo_changed),
                    NULL);
  g_signal_connect ((gpointer) pmSplitTunnelCheckBtn, "toggled",
                    G_CALLBACK (on_pmSplitTunnelCheckBtn_toggled),
                    NULL);
  g_signal_connect ((gpointer) pmCancelBtn, "clicked",
                    G_CALLBACK (on_pmCancelBtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) pmRembtn, "clicked",
                    G_CALLBACK (on_pmRembtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) pmSavBtn, "clicked",
                    G_CALLBACK (on_pmSavBtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) pmAddBtn, "clicked",
                    G_CALLBACK (on_pmAddBtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) mainHelpBtn, "clicked",
                    G_CALLBACK (on_mainHelpBtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) mainDisconnectBtn, "clicked",
                    G_CALLBACK (on_mainDisconnectBtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) mainCancelBtn, "clicked",
                    G_CALLBACK (on_mainCancelBtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) mainConnectBtn, "clicked",
                    G_CALLBACK (on_mainConnectBtn_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (profileLabel), profileCombo);
  gtk_label_set_mnemonic_widget (GTK_LABEL (gwtypeLabel), gwtypeCombo);
  gtk_label_set_mnemonic_widget (GTK_LABEL (gwLabel), gwEntry);
  gtk_label_set_mnemonic_widget (GTK_LABEL (authenticateLabel), authenticateCombo);
  gtk_label_set_mnemonic_widget (GTK_LABEL (auth1label), auth1Combo);
  gtk_label_set_mnemonic_widget (GTK_LABEL (auth2Label), auth2Entry);
  gtk_label_set_mnemonic_widget (GTK_LABEL (pmProfileNameLabel), pmprofileNameEntry);
  gtk_label_set_mnemonic_widget (GTK_LABEL (pmGwIP), pmGwEntry);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (vpnlogin, vpnlogin, "vpnlogin");
  GLADE_HOOKUP_OBJECT (vpnlogin, mainVBox, "mainVBox");
  GLADE_HOOKUP_OBJECT (vpnlogin, mainNotebook, "mainNotebook");
  GLADE_HOOKUP_OBJECT (vpnlogin, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (vpnlogin, gwMainTable, "gwMainTable");
  GLADE_HOOKUP_OBJECT (vpnlogin, profileLabel, "profileLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, profileCombo, "profileCombo");
  GLADE_HOOKUP_OBJECT (vpnlogin, gwtypeLabel, "gwtypeLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, gwtypeCombo, "gwtypeCombo");
  GLADE_HOOKUP_OBJECT (vpnlogin, gwLabel, "gwLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, authenticateLabel, "authenticateLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, authenticateCombo, "authenticateCombo");
  GLADE_HOOKUP_OBJECT (vpnlogin, gwEntry, "gwEntry");
  GLADE_HOOKUP_OBJECT (vpnlogin, authFrame, "authFrame");
  GLADE_HOOKUP_OBJECT (vpnlogin, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (vpnlogin, table2, "table2");
  GLADE_HOOKUP_OBJECT (vpnlogin, auth1label, "auth1label");
  GLADE_HOOKUP_OBJECT (vpnlogin, auth1Combo, "auth1Combo");
  GLADE_HOOKUP_OBJECT (vpnlogin, auth2Label, "auth2Label");
  GLADE_HOOKUP_OBJECT (vpnlogin, auth2Entry, "auth2Entry");
  GLADE_HOOKUP_OBJECT (vpnlogin, authenticateHeadingLabel, "authenticateHeadingLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, gwPanel, "gwPanel");
  GLADE_HOOKUP_OBJECT (vpnlogin, connPanelVBox, "connPanelVBox");
  GLADE_HOOKUP_OBJECT (vpnlogin, ConnectionStatusFrame, "ConnectionStatusFrame");
  GLADE_HOOKUP_OBJECT (vpnlogin, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (vpnlogin, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (vpnlogin, table9, "table9");
  GLADE_HOOKUP_OBJECT (vpnlogin, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (vpnlogin, label91, "label91");
  GLADE_HOOKUP_OBJECT (vpnlogin, connStatusLabel, "connStatusLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, connLabel1, "connLabel1");
  GLADE_HOOKUP_OBJECT (vpnlogin, connLabel, "connLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, connStatusFrameLabel, "connStatusFrameLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, connDetailsTable, "connDetailsTable");
  GLADE_HOOKUP_OBJECT (vpnlogin, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (vpnlogin, connIPAddress, "connIPAddress");
  GLADE_HOOKUP_OBJECT (vpnlogin, connUptime, "connUptime");
  GLADE_HOOKUP_OBJECT (vpnlogin, label109, "label109");
  GLADE_HOOKUP_OBJECT (vpnlogin, label108, "label108");
  GLADE_HOOKUP_OBJECT (vpnlogin, connectionPanel, "connectionPanel");
  GLADE_HOOKUP_OBJECT (vpnlogin, dynamicsVbox, "dynamicsVbox");
  GLADE_HOOKUP_OBJECT (vpnlogin, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (vpnlogin, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (vpnlogin, table4, "table4");
  GLADE_HOOKUP_OBJECT (vpnlogin, label21, "label21");
  GLADE_HOOKUP_OBJECT (vpnlogin, label22, "label22");
  GLADE_HOOKUP_OBJECT (vpnlogin, label25, "label25");
  GLADE_HOOKUP_OBJECT (vpnlogin, label26, "label26");
  GLADE_HOOKUP_OBJECT (vpnlogin, label27, "label27");
  GLADE_HOOKUP_OBJECT (vpnlogin, label28, "label28");
  GLADE_HOOKUP_OBJECT (vpnlogin, label29, "label29");
  GLADE_HOOKUP_OBJECT (vpnlogin, label30, "label30");
  GLADE_HOOKUP_OBJECT (vpnlogin, saStasLabel, "saStasLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (vpnlogin, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (vpnlogin, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (vpnlogin, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (vpnlogin, saDetailsLabel, "saDetailsLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, dynamicsPanel, "dynamicsPanel");
  GLADE_HOOKUP_OBJECT (vpnlogin, profileManagerVbox, "profileManagerVbox");
  GLADE_HOOKUP_OBJECT (vpnlogin, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (vpnlogin, table21, "table21");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmProfileLabel, "pmProfileLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmprofileCombo, "pmprofileCombo");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmNotebook, "pmNotebook");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmGeneralTable, "pmGeneralTable");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmProfileNameLabel, "pmProfileNameLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmprofileNameEntry, "pmprofileNameEntry");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmGwTypeLabel, "pmGwTypeLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmAuthframe, "pmAuthframe");
  GLADE_HOOKUP_OBJECT (vpnlogin, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (vpnlogin, table23, "table23");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmUserCertLabel, "pmUserCertLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmauthCombo, "pmauthCombo");
  GLADE_HOOKUP_OBJECT (vpnlogin, label96, "label96");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmAuthenticateLabel, "pmAuthenticateLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmauthenticateCombo, "pmauthenticateCombo");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmGwIP, "pmGwIP");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmgwtypeCombo, "pmgwtypeCombo");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmGwEntry, "pmGwEntry");
  GLADE_HOOKUP_OBJECT (vpnlogin, label110, "label110");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmauthtypeCombo, "pmauthtypeCombo");
  GLADE_HOOKUP_OBJECT (vpnlogin, label76, "label76");
  GLADE_HOOKUP_OBJECT (vpnlogin, table25, "table25");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmPh1DhLabel, "pmPh1DhLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmPh2PfsLabel, "pmPh2PfsLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, label116, "label116");
  GLADE_HOOKUP_OBJECT (vpnlogin, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (vpnlogin, addbtn, "addbtn");
  GLADE_HOOKUP_OBJECT (vpnlogin, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (vpnlogin, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (vpnlogin, image19, "image19");
  GLADE_HOOKUP_OBJECT (vpnlogin, label118, "label118");
  GLADE_HOOKUP_OBJECT (vpnlogin, rembtn, "rembtn");
  GLADE_HOOKUP_OBJECT (vpnlogin, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (vpnlogin, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (vpnlogin, image20, "image20");
  GLADE_HOOKUP_OBJECT (vpnlogin, label119, "label119");
  GLADE_HOOKUP_OBJECT (vpnlogin, scrolledwindow7, "scrolledwindow7");
  GLADE_HOOKUP_OBJECT (vpnlogin, ph2treeview, "ph2treeview");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmPh1ModeLabel, "pmPh1ModeLabel");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmPh1ModeCombo, "pmPh1ModeCombo");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmPh1DhCombo, "pmPh1DhCombo");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmPh2DhCombo, "pmPh2DhCombo");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmSplitTunnelCheckBtn, "pmSplitTunnelCheckBtn");
  GLADE_HOOKUP_OBJECT (vpnlogin, label114, "label114");
  GLADE_HOOKUP_OBJECT (vpnlogin, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (vpnlogin, hbuttonbox5, "hbuttonbox5");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmCancelBtn, "pmCancelBtn");
  GLADE_HOOKUP_OBJECT (vpnlogin, hbuttonbox6, "hbuttonbox6");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmRembtn, "pmRembtn");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmSavBtn, "pmSavBtn");
  GLADE_HOOKUP_OBJECT (vpnlogin, pmAddBtn, "pmAddBtn");
  GLADE_HOOKUP_OBJECT (vpnlogin, profilePanel, "profilePanel");
  GLADE_HOOKUP_OBJECT (vpnlogin, mainWindowHbox, "mainWindowHbox");
  GLADE_HOOKUP_OBJECT (vpnlogin, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (vpnlogin, mainHelpBtn, "mainHelpBtn");
  GLADE_HOOKUP_OBJECT (vpnlogin, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (vpnlogin, mainDisconnectBtn, "mainDisconnectBtn");
  GLADE_HOOKUP_OBJECT (vpnlogin, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (vpnlogin, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (vpnlogin, image15, "image15");
  GLADE_HOOKUP_OBJECT (vpnlogin, label103, "label103");
  GLADE_HOOKUP_OBJECT (vpnlogin, mainCancelBtn, "mainCancelBtn");
  GLADE_HOOKUP_OBJECT (vpnlogin, mainConnectBtn, "mainConnectBtn");
  GLADE_HOOKUP_OBJECT (vpnlogin, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (vpnlogin, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (vpnlogin, image16, "image16");
  GLADE_HOOKUP_OBJECT (vpnlogin, label104, "label104");
  GLADE_HOOKUP_OBJECT_NO_REF (vpnlogin, tooltips, "tooltips");

  gtk_widget_grab_focus (gwPanel);
  gtk_window_add_accel_group (GTK_WINDOW (vpnlogin), accel_group);

  return vpnlogin;
}

